
from langchain.agents import create_agent
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
import os
from dotenv import load_dotenv

load_dotenv()

# --- 1. Define Dummy Tools ---
@tool
def read_file(file_path: str) -> str:
    """Read a file."""
    return f"Content of {file_path}"

@tool
def write_file(file_path: str, content: str) -> str:
    """Write to a file."""
    return f"Wrote content to {file_path}"

@tool
def run_tests(test_file: str) -> str:
    """Run tests."""
    return "All tests passed"

# --- 2. Implement Custom Middleware ---
# The error "type object 'TodoListMiddleware' has no attribute 'wrap_tool_call'"
# implies create_agent checks for this. We need a compliant class.

class TodoListMiddleware:
    """Middleware to track todo items generated by the agent."""
    
    def __init__(self):
        self.todos = []

    def before_model(self, state, runtime):
        # Can inspect state or inject system prompts here
        # For simplicity, just logging or pass
        return None

    def after_tools(self, state, runtime):
        # Can inspect tool outputs here
        # For this demo, we might want to capture "write_file" as a "completed todo" maybe?
        return None
        
    def wrap_tool_call(self, tool, runtime):
        """Standard middleware method to wrap tool execution."""
        # This method is required by the create_agent factory it seems.
        # It must return the tool or a wrapper.
        return tool

    # To actually "return" todos in the result as the user asked ("i don't see any todo"),
    # we might need to rely on the agent's output matching a refined schema or
    # adding a specific 'todos' key if the agent supports structured output.
    # However, create_agent generally returns the final model output/messages.
    # We can print them here to show they exist.

print("--- Initializing Agent with Fixed Middleware ---")

try:
    if not os.environ.get("OPENAI_API_KEY"):
        print("Warning: OPENAI_API_KEY not set")

    # Define a tool specifically for Todo management if we want structured todos
    # OR rely on the prompt to generate a list. 
    # The user prompt: "Create a todo list..." implies the OUTPUT should be the list.
    
    agent = create_agent(
        model="gpt-4o",
        tools=[read_file, write_file, run_tests],
        middleware=[TodoListMiddleware()],
    )
    
    print("Invoking agent...")
    response = agent.invoke({"messages": [{"role": "user", "content": "Create a todo list for implementing a new feature in langchain."}]})
    
    print("\n--- Response ---")
    print(response)
    
    # If the user expects a specific "result" variable to contain todos separate from messages:
    # That usually requires a custom agent or a middleware that modifies the return dict.
    # langgraph agents return a dict with 'messages' key usually.

except TypeError as e:
    print(f"\n[Error Fix needed]: {e}")
    # If wrap_tool_call is expected on the INSTANCE or CLASS? error said "type object ... has no attribute".
    # That might imply it accessed TodoListMiddleware.wrap_tool_call (class method?) or I passed the class instead of instance?
    # User code: middleware=[TodoListMiddleware()] -> Instance.
    # Let's ensure methods are instance methods.
except Exception as e:
    import traceback
    traceback.print_exc()
